version: "3.4"

services:
  MySql_users:
    image: library/mysql:8
    container_name: users-api-mysql
    hostname: mysql
    restart: always
    ports:
      - 3320:3306
    environment:
      - MYSQL_DATABASE=testdbdocker
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=root_pwd
        
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d